Repository sync-stack-dev/slid-todo, pull requests merged in 2024-12, with the labels that each got.

#51 Feature/SCRUM 69/update sidebar
  slid-todo/cypress/e2e/dashboard.cy.tsx
  slid-todo/public/click-sounds.wav
  slid-todo/public/svgs/circle.tsx
  slid-todo/src/app/(routes)/dashboard/components/progress-block/circleProgress.tsx
  slid-todo/src/app/(routes)/dashboard/components/recent-todo-block/recent-container.tsx
  slid-todo/src/app/(routes)/dashboard/page.tsx
  slid-todo/src/components/shared/app-sidebar/app-sidebar.tsx
  slid-todo/src/components/shared/app-sidebar/components/hamburger-button.tsx
  slid-todo/src/components/shared/theme-toggle.tsx
  slid-todo/src/components/ui/container.tsx
  slid-todo/src/components/ui/password-input.tsx
  slid-todo/src/components/ui/progress.tsx
  slid-todo/tailwind.config.ts
Labels: 🐛bug

#61 Design/note page
  slid-todo/package-lock.json
  slid-todo/public/svgs/profile.tsx
  slid-todo/src/app/(routes)/(todos)/todos/page.tsx
  slid-todo/src/app/(routes)/notes/[goalId]/components/note-card.tsx
  slid-todo/src/app/(routes)/notes/[goalId]/components/note-meatball-btn.tsx
  slid-todo/src/app/(routes)/notes/[goalId]/layout.tsx
  slid-todo/src/app/(routes)/notes/[goalId]/page.tsx
  slid-todo/src/app/(routes)/notes/create/[todoId]/components/note-create-form.tsx
  slid-todo/src/app/(routes)/notes/create/[todoId]/components/note-create-header.tsx
  slid-todo/src/app/(routes)/notes/create/[todoId]/components/note-create-info.tsx
  slid-todo/src/app/(routes)/notes/create/[todoId]/components/utils/create-validation.ts
  slid-todo/src/app/(routes)/notes/create/[todoId]/layout.tsx
  slid-todo/src/app/(routes)/notes/create/[todoId]/page.tsx
  slid-todo/src/app/(routes)/notes/edit/[noteId]/components/note-edit-form.tsx
  slid-todo/src/app/(routes)/notes/edit/[noteId]/components/note-edit-header.tsx
  slid-todo/src/app/(routes)/notes/edit/[noteId]/components/note-edit-info.tsx
  slid-todo/src/app/(routes)/notes/edit/[noteId]/components/utils/edit-validation.ts
  slid-todo/src/app/(routes)/notes/edit/[noteId]/layout.tsx
  slid-todo/src/app/(routes)/notes/edit/[noteId]/page.tsx
  slid-todo/src/app/(routes)/notes/layout.tsx
  slid-todo/src/app/globals.css
  slid-todo/src/components/shared/badges/todo-badge.tsx
  slid-todo/src/components/shared/editor/note-write-editor.tsx
  slid-todo/src/components/shared/editor/note-write-toolbar.tsx
  slid-todo/src/components/shared/editor/paint-bucket-input.tsx
  slid-todo/src/components/shared/link-embed/link-embed.tsx
  slid-todo/src/hooks/note/use-note.ts
  slid-todo/src/hooks/todo/use-todos.ts
  slid-todo/src/providers/theme-provider.tsx
Labels: 👀 review needed

#66 Feature/scrum 86/note unit test
  .github/workflows/unit-test.yml
  slid-todo/__tests__/data/note.ts
  slid-todo/__tests__/notes/note-card-action.test.tsx
  slid-todo/__tests__/notes/note-crud.test.tsx
  slid-todo/__tests__/notes/note-list.test.tsx
  slid-todo/jest.config.ts
  slid-todo/package-lock.json
  slid-todo/package.json
  slid-todo/src/app/(routes)/notes/create/[todoId]/components/note-create-form.tsx
  slid-todo/src/components/shared/editor/note-write-editor.tsx
  slid-todo/src/components/shared/note-viewer/index.tsx
Labels: 👀 review needed

#74 8차 병합
  slid-todo/src/app/(routes)/(todos)/todos/page.tsx
  slid-todo/src/app/(routes)/dashboard/page.tsx
  slid-todo/src/app/(routes)/goals/[goalId]/page.tsx
  slid-todo/src/app/(routes)/notes/[goalId]/page.tsx
  slid-todo/src/app/(routes)/notes/create/[todoId]/page.tsx
  slid-todo/src/app/(routes)/notes/edit/[noteId]/page.tsx
  slid-todo/src/app/(routes)/notes/layout.tsx
  slid-todo/src/components/shared/app-sidebar/components/app-sidebar-trigger.tsx
  slid-todo/src/components/shared/editor/note-write-toolbar.tsx
Labels: 🔀 main

#76 Feature/scrum 91/todos unit test
  slid-todo/__tests__/data/test-utils.tsx
  slid-todo/__tests__/data/todo.ts
  slid-todo/__tests__/todos/components/todo-filter.test.tsx
  slid-todo/__tests__/todos/components/todo-header.test.tsx
  slid-todo/__tests__/todos/components/todo-index.test.tsx
  slid-todo/__tests__/todos/components/todo-list-content.test.tsx
  slid-todo/__tests__/todos/components/utils.test.ts
  slid-todo/__tests__/todos/todos-page.test.tsx
  slid-todo/src/app/(routes)/(todos)/todos/components/todo-header.tsx
  slid-todo/src/app/(routes)/(todos)/todos/components/todo-list-content.tsx
  slid-todo/src/app/(routes)/(todos)/todos/page.tsx
  slid-todo/src/app/(routes)/dashboard/components/goal-todo-block/goal-todo-container.tsx
  slid-todo/src/app/(routes)/goals/[goalId]/components/goal-list-content.tsx
  slid-todo/src/components/shared/app-sidebar/components/app-sidebar-user-info.tsx
  slid-todo/src/components/shared/loading.tsx
  slid-todo/src/components/shared/todo-list/actions/index.tsx
  slid-todo/src/components/shared/todo-list/todo-item-checkbox.tsx
  slid-todo/src/hooks/todo/use-todo-actions.ts
Labels: ✅ test

#83 feat: goal-page 관련 단위 테스트 추가
  slid-todo/__tests__/goals/[goalId]/components/goal-list-content.test.tsx
  slid-todo/__tests__/goals/[goalId]/goal-page.test.tsx
Labels: ✅ test

#85 Feature/scrum 91/todos hooks unit test
  slid-todo/__tests__/hooks/todo/use-todo-actions.test.tsx
  slid-todo/__tests__/hooks/todo/use-todos.test.ts
  slid-todo/src/hooks/todo/use-todos.ts
Labels: ✅ test

#86 10차 병합
  slid-todo/__tests__/goals/[goalId]/components/goal-list-content.test.tsx
  slid-todo/__tests__/goals/[goalId]/goal-page.test.tsx
  slid-todo/__tests__/hooks/todo/use-todo-actions.test.tsx
  slid-todo/__tests__/hooks/todo/use-todos.test.ts
  slid-todo/__tests__/login/Login-form.test.tsx
  slid-todo/__tests__/signup/Signup-form.test.tsx
  slid-todo/src/app/(routes)/dashboard/components/goal-todo-block/goal-todo-container.tsx
  slid-todo/src/app/(routes)/dashboard/components/goal-todo-block/goal-todo.tsx
  slid-todo/src/app/(routes)/dashboard/layout.tsx
  slid-todo/src/app/(routes)/dashboard/page.tsx
  slid-todo/src/app/(routes)/goals/[goalId]/components/goal-list-content.tsx
  slid-todo/src/app/(routes)/notes/create/[todoId]/components/note-create-form.tsx
  slid-todo/src/app/(routes)/notes/create/[todoId]/components/utils/create-validation.ts
  slid-todo/src/app/(routes)/notes/create/[todoId]/layout.tsx
  slid-todo/src/app/(routes)/notes/create/[todoId]/page.tsx
  slid-todo/src/app/(routes)/notes/edit/[noteId]/components/note-edit-form.tsx
  slid-todo/src/app/(routes)/notes/edit/[noteId]/components/utils/edit-validation.ts
  slid-todo/src/app/globals.css
  slid-todo/src/components/shared/app-sidebar/components/app-sidebar-footer.tsx
  slid-todo/src/components/shared/app-sidebar/components/app-sidebar-user-info.tsx
  slid-todo/src/components/shared/form-modal/components/title-field.tsx
  slid-todo/src/components/shared/link-embed/link-embed.tsx
  slid-todo/src/components/shared/note-viewer/embed-content.tsx
  slid-todo/src/components/shared/note-viewer/index.tsx
  slid-todo/src/hooks/goals/use-goal.ts
  slid-todo/src/hooks/todo/use-todos.ts
  slid-todo/src/hooks/use-media-query.ts
Labels: 🔀 main
